### ISSUE TITLE
Manage Preference Sets

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#287]
Make it easier to copy sets of preferences from one project template to another. 

Maybe handle this by introducing the notion of Curricular Units, ala GEM-STEP.  The Unit becomes a template for defining sets of features (node, edge definitions specifically), e.g. there could be a "history" oriented unit vs a "literature" set?

Joshua writes:
The part that is not easy is copying over the criteria or other descriptions. Ideally we'd want a way to do that simply. In Net.Create, we usually handle it by making a network then duplicating it by hand (both the data, if any, and the template) and renaming. This works OK with multiplex, but would likely not be all that doable with the 360 if 360 runs just net.create without some layer.

## Candidate Features?
- [ ] Allow importing/exporting sections of the definitions (e.g. just comment types, just. node types, etc.)
- [ ] Detach name of template from project so that multiple projects can share the "Historical Roman Texts" Curriculum Unit, for instance?
- [ ] How do you handle variations?  e.g. you don't want to clobber the whole "Historical Roman Texts" unit, but you also want to allow managers to add new types as necessary?
