### ISSUE TITLE
Full provenance re-vamp

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#55]
Adding from this pull request https://github.com/netcreateorg/netcreate-itest/pull/39 

- [ ] `created`, `updated`, `revision` parameters are "burned in" to the Provenance tab currently and do not honor toml template hidden settings.

From "VFOI ITEST Meeting Notes and Agendas 2023-2024"

Provenance

Another text field, maybe called “Source”
1. By default, add something like “Created by a student” or “Created by student TOKEN” and then “on May 10, 10:100am”
2. We can edit it, so we’ll edit it to say “Added by teachers” or “From wikipedia” or whatever. 

* Long-term, this will include sub-fields, and history, and the source will be auto-generated and kids will only be able to edit sub-fields (maybe), but for now this lets us tinker
* Note: Nodes and Edges
* Note: Add to filter as string
   1. Long-term filter by name, date, others

**Comment by benloh** [comment]
## Settings
* `isProvenance = true` will add the item to the "Provenance" tab's "Provenance" section (not the "History" section)
* The "History" section will have "Created", "Updated", and "Revision" automatically displayed, unless they are "hidden" by the template.
* `hidden = true` will be honored in the Node/Edge display tabs
* The `Created` and `Updated` fields in the History section are actually a combination of `created` + `createdby`, and `updated` + `updatedby` fields
* Add a new type of field "source" that defaults to "Created by <token> on <date>" but is otherwise editable as text.  e.g. someone can edit it to show "Added by teachers".
* Any other custom field can be added to the "Provenance" section by adding `isProvenance = true` including `number`, `string`, and even `selection` fields.  That would enable you to add something like a popup menu where you can select arbitrary options like "Wikipedia", "Teacher", "Book" etc.

Example
```
Provenance Tab

Provenance Section
* SOURCE: Created by BEN-QPIX on May 10, 10:10am

History Section
* Created: DEMO-A-JW7, 1/4/2025, 10:34:58 AM
* Updated: DEMO-A-JW7, 1/4/2025, 10:35:00 AM
* Revision: 2
```

## Caveats / Overrides
* `hidden = true` are always exported and imported if they are built-in fields

@jdanish does this sound like the right implementation of Provenance for now?  Or is there something else?  (Adding it to tables and filters are separate issues).


# To Do
- [x] Hide Provenance and History sections if `hidden = true`
   - [x] If `created` is hidden, hide the "Created" line
   - [x] If `createdby` is hidden, only hide the user token 
- [x] Add a `infoOrigin` field type that initially defaults to `createdby` + `created`

**Comment by jdanish** [comment]
Assuming the label for source can be changed that sounds great to me! @kalanicraig are we missing anything big?

**Comment by kalanicraig** [comment]
This looks good to me.

**Comment by benloh** [comment]
"SOURCE" would just be another custom field.  So yeah, you can name it whatever you want.   The definition would probably look something like this:

```
[nodeDefs.reference]       // you can also call this 'nodeDefs.source' or 'nodeDefs.citation' etc 
type = "source"            // this would be the name of the specialized type
displayLabel = "source"
exportLabel = "Info Source"
help = "Where did the information come from?"
includeInGraphTooltip = true
isProvenance = true
hidden = false
```

**Comment by jdanish** [comment]
Perfect.

**Comment by benloh** [comment]
@jdanish One revision.  Edges already have a `source` field, so it would be confusing to have a type of field called `source`.   So I'm going to propose we call it `reference` type.  We also had a historical field called `citation`, but I feel like that might be too specific.  Any thoughts on another name?

```
[nodeDefs.reference]       // you can also call this 'nodeDefs.source' or 'nodeDefs.citation' etc 
type = "reference"            // this would be the name of the specialized type
displayLabel = "InfoSource"
exportLabel = "Info Source"
help = "Where did the information come from?"
includeInGraphTooltip = true
isProvenance = true
hidden = false
```

**Comment by kalanicraig** [comment]
InfoOrigin

**Comment by jdanish** [comment]
InfoOrigin works for me, or I was going to suggest DataSource... I defer to Kalani.

**Comment by kalanicraig** [comment]
Origin helps us understand the intermediary between the academic
citation/reference and the person/place from whom that academic citation
originated. DataSource might be too specific for some of our less technical
audiences.

**Comment by jdanish** [comment]
OK, then I pitch informationorigin and either way we can use whatever label we want.

**Comment by benloh** [comment]
Awesome!  `infoOrigin` it is!  Thanks!

```
[nodeDefs.origin]               // you can also call this 'nodeDefs.source' or 'nodeDefs.citation' etc 
type = "infoOrigin"             // this would be the name of the specialized type
displayLabel = "Information Origin"
exportLabel = "InfoOrigin"
help = "Where did the information come from?"
includeInGraphTooltip = true
isProvenance = true
hidden = false
```

**Comment by benloh** [comment]
Implemented with 7e39647e448eef3c882537d55920675fae16b3b3, 40876fefc3dd83def4575561c793bef07801b7b3, and  d7b6e2ca6a8517e2c1f4f83cca66891314ad372c
